version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=docker
    depends_on:
      - postgres